'use client';
// THESIS: A merchant edits one store section at a time, without WordPress chrome.
// OWN-WORLD: Turquoise merchant studio, dark rail, thumbnail-led navigation.
// STORY: Select a section, edit its content, preview privately, publish explicitly.
// FIRST VIEWPORT: Right rail, task tabs, section list, focused editor, compact preview.
// FORM: User-approved comp 1; task-tabs workbench, surface seed 99920963, structure 6.
import {useEffect,useId,useRef,useState} from 'react';
import Icon from '../components/icons';
import {defaultDesign} from '../../lib/design';
import ContentSettings from './content-settings';
import {PresetGallery,ConnectionPlanner} from './setup-tools';
import {applyStorePreset} from '../../lib/store-presets';
import {Switch,Badge} from '../components/vibefarsi/controls';

const types={hero:'اسلایدر تصویری',features:'خدمات فروشگاه',banners:'بنرهای تصویری',products:'ویترین محصولات',categories:'دسته‌بندی محصولات','text-image':'تصویر و متن',faq:'سؤالات متداول',spacer:'فاصله‌گذار'};
const tabs={home:'صفحهٔ اصلی',presets:'چیدمان‌های آماده',identity:'هویت و رنگ',menus:'منوها',content:'صفحات و محتوا',display:'نمایش و خدمات',connection:'برنامهٔ اتصال',history:'تاریخچه'};
const fa=value=>Number(value).toLocaleString('fa-IR');
const copy=value=>JSON.parse(JSON.stringify(value));
export async function api(action,body={}){
  const response=await fetch(`/api/manage/${action}`,{method:'POST',headers:body instanceof FormData?{}:{'Content-Type':'application/json'},body:body instanceof FormData?body:JSON.stringify(body),cache:'no-store'});
  const data=await response.json();if(!response.ok){const error=new Error(data.error||'درخواست انجام نشد.');error.status=response.status;throw error;}return data;
}
function Field({label,value,onChange,multiline=false,type='text',hint,...props}){const id=useId();return <label className="manage-field" htmlFor={id}><span>{label}</span>{multiline?<textarea id={id} value={value??''} onChange={e=>onChange(e.target.value)} rows={4} {...props}/>:<input id={id} type={type} value={value??''} onChange={e=>onChange(type==='number'?Number(e.target.value):e.target.value)} {...props}/>} {hint&&<small>{hint}</small>}</label>;}
function Select({label,value,onChange,options}){return <label className="manage-field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{Object.entries(options).map(([key,text])=><option key={key} value={key}>{text}</option>)}</select></label>;}
function Toggle({label,checked,onChange}){return <div className="manage-toggle"><Switch aria-label={label} checked={checked} onCheckedChange={onChange}/><span>{label}</span></div>;}
function Move({index,total,onMove,label}){return <span className="manage-move"><button type="button" disabled={index===0} onClick={()=>onMove(index,-1)} aria-label={`انتقال ${label} به بالا`}>↑</button><button type="button" disabled={index===total-1} onClick={()=>onMove(index,1)} aria-label={`انتقال ${label} به پایین`}>↓</button></span>;}
function move(items,index,delta){const next=[...items];[next[index],next[index+delta]]=[next[index+delta],next[index]];return next;}

export default function Manager(){
  const [document,setDocument]=useState(null),[design,setDesign]=useState(null),[phase,setPhase]=useState('loading'),[tab,setTab]=useState('home'),[selected,setSelected]=useState(0),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[preview,setPreview]=useState(''),[history,setHistory]=useState([]),[mediaTarget,setMediaTarget]=useState(null),[adding,setAdding]=useState(false),[reauth,setReauth]=useState(false);
  const dirty=Boolean(design&&JSON.stringify(design)!==JSON.stringify(document?.design));
  const alive=useRef(true),draftRef=useRef(design);draftRef.current=design;
  const titleRef=useRef(null),focusPreset=useRef(false);
  useEffect(()=>{if(focusPreset.current&&tab==='home'){titleRef.current?.focus();focusPreset.current=false;}},[tab]);
  async function load(){setError('');try{const result=await api('read');setDocument(result);setDesign(copy(result.design));setPhase('ready');setSelected(0);}catch(e){setPhase(e.status===401?'login':'error');setError(e.status===401?'':e.message);}}
  useEffect(()=>{alive.current=true;load();return()=>{alive.current=false;};},[]);
  useEffect(()=>{const warn=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
  function update(next){setDesign(next);setNotice('');setPreview('');}
  function setSettings(changes){update({...design,settings:{...design.settings,...changes}});}
  async function selectPreset(id){if(!window.confirm('چیدمان صفحهٔ اصلی و رنگ‌های پیش‌نویس جایگزین شوند؟ بخش‌های فعلی پیش‌نویس کنار گذاشته می‌شوند. نام، لوگو، منوها، محصولات و سفارش‌ها تغییر نمی‌کنند. تا انتشار، فروشگاه فعلی حفظ می‌شود.'))return;const snapshot=JSON.stringify(design);await action('catalog',{kind:'category',search:''},result=>{if(JSON.stringify(draftRef.current)!==snapshot){setNotice('طراحی تغییر کرده است؛ چیدمان را دوباره انتخاب کنید.');return;}update(applyStorePreset(design,id,result.items));setSelected(0);focusPreset.current=true;setTab('home');setNotice('چیدمان در پیش‌نویس قرار گرفت. پیش از انتشار، محتوا و پیش‌نمایش را بررسی کنید.');});}
  function setSection(changes){update({...design,sections:design.sections.map((s,i)=>i===selected?{...s,...changes}:s)});}
  async function action(name,body,done){setBusy(name);setError('');setNotice('');try{const result=await api(name,body);done?.(result);}catch(e){setError(e.message);if(e.status===401)setReauth(true);}finally{setBusy('');}}
  function publish(){const submitted=copy(design);action('save',{design:submitted,revision:document.revision},result=>{setDocument(result);if(JSON.stringify(draftRef.current)===JSON.stringify(submitted))setDesign(copy(result.design));setNotice('تغییرات منتشر شد؛ فروشگاه به‌روز است.');});}
  function showHistory(){setTab('history');action('history',{},r=>setHistory(r.items));}
  function restore(id){if(!window.confirm('این نسخه جایگزین طراحی منتشرشده می‌شود. تغییرات ذخیره‌نشدهٔ این صفحه کنار گذاشته می‌شود. ادامه می‌دهید؟'))return;action('restore',{id,revision:document.revision},r=>{setDocument(r);setDesign(copy(r.design));setNotice('نسخهٔ انتخاب‌شده بازگردانده شد.');setSelected(0);setTab('home');});}
  function add(type){const sample=defaultDesign.sections.find(s=>s.type===type);const section=sample?{...copy(sample),title:types[type],items:[]}:{type,title:types[type],enabled:true,visibility:'all',items:[],columns:4,mobileColumns:2,gap:20,spacing:24,padding:0};update({...design,sections:[...design.sections,section]});setSelected(design.sections.length);setAdding(false);}
  function reorder(index,delta){update({...design,sections:move(design.sections,index,delta)});setSelected(index+delta);}
  function remove(){if(!window.confirm('این بخش از چیدمان حذف شود؟ حذف پس از انتشار در فروشگاه اعمال می‌شود.'))return;update({...design,sections:design.sections.filter((_,i)=>i!==selected)});setSelected(Math.max(0,selected-1));}
  if(phase==='loading')return <main className="manage-app manage-loading"><div className="manage-skeleton"/><div className="manage-skeleton"/><p role="status">در حال دریافت مدیریت فروشگاه…</p></main>;
  if(phase==='login')return <Login onLogin={load}/>;
  if(phase==='error')return <main className="manage-app manage-login"><h1>مدیریت فروشگاه در دسترس نیست</h1><p role="alert">{error}</p><button onClick={load}>تلاش مجدد</button><a href="/">بازگشت به فروشگاه</a></main>;
  const section=design.sections[selected];
  return <div className="manage-app">
    <aside className="manage-rail"><a href="/manage" className="manage-brand"><Icon name="grid"/><span>مدیریت فروشگاه<small>{design.settings.name}</small></span></a><nav aria-label="مدیریت فروشگاه"><button className="is-current" onClick={()=>setTab('home')}><Icon name="grid"/>ظاهر فروشگاه</button><a href="/manage/store"><Icon name="bag"/>محصولات و عملیات فروشگاه</a><a href="/" target="_blank" rel="noopener"><Icon name="eye"/>مشاهدهٔ فروشگاه</a><button onClick={()=>{setTab('help');}}><Icon name="info"/>راهنمای مدیریت</button></nav><div className="manage-rail-foot"><p>داده‌ها در وردپرس شما ذخیره می‌شوند.</p><button disabled={Boolean(busy)} onClick={()=>{if(!dirty||window.confirm('از پنل خارج شوید؟ تغییرات منتشرنشده ذخیره نمی‌شوند.'))action('logout',{},()=>{setPhase('login');setDocument(null);setDesign(null);});}}><Icon name="user"/>خروج از مدیریت</button></div></aside>
    <div className="manage-main"><header className="manage-toolbar"><div className="manage-store-identity"><span className="manage-avatar">{design.settings.name.slice(0,1)}</span><div><strong>{design.settings.name}</strong><Badge variant={dirty?'warning':'success'} className="manage-state"><span className={dirty?'is-dirty':''}/>{dirty?'تغییرات منتشرنشده دارید':'همهٔ تغییرات منتشر شده‌اند'}</Badge></div></div><div className="manage-actions"><button disabled={Boolean(busy)} onClick={()=>{const snapshot=JSON.stringify(design);action('preview',{design},r=>{if(JSON.stringify(draftRef.current)===snapshot)setPreview(r.url);else setNotice('طراحی تغییر کرده است؛ پیش‌نمایش تازه بسازید.');});}}><Icon name="eye"/>{busy==='preview'?'آماده‌سازی…':'پیش‌نمایش'}</button><button className="manage-primary" disabled={!dirty||Boolean(busy)} onClick={publish}><Icon name="check"/>{busy==='save'?'در حال انتشار…':'انتشار تغییرات'}</button></div></header>
      <nav className="manage-tabs" aria-label="تنظیمات ظاهر">{Object.entries(tabs).map(([key,label])=><button key={key} aria-current={tab===key?'page':undefined} onClick={()=>key==='history'?showHistory():setTab(key)}><Icon name={{home:'home',presets:'grid',identity:'heart',menus:'menu',content:'order',display:'eye',connection:'pin',history:'order'}[key]}/>{label}</button>)}</nav>
      <main className="manage-content" id="manage-content"><div className="manage-title"><div><h1 ref={titleRef} tabIndex={-1}>{tabs[tab]||'راهنمای مدیریت'}</h1><p>{tab==='home'?'بخش‌ها را مرتب کنید و محتوای هر بخش را همین‌جا تغییر دهید.':tab==='connection'?'برنامه‌ریزی پیش از استقرار؛ دکمه‌های پیش‌نمایش و انتشار بالا فقط مربوط به ظاهر فروشگاه هستند.':'تنظیمات فروشگاه بدون بیلد دوباره روی سایت اعمال می‌شوند.'}</p></div>{tab==='home'&&<button onClick={()=>setAdding(!adding)} disabled={design.sections.length>=40}>+ افزودن بخش</button>}</div>
        {error&&<div role="alert" className="manage-message is-error"><p>{error}</p>{error.includes('پنجره')&&<button onClick={()=>{if(window.confirm('تغییرات ذخیره‌نشده کنار گذاشته و نسخهٔ تازه دریافت شود؟'))load();}}>دریافت نسخهٔ تازه</button>}</div>}
        {notice&&<p role="status" className="manage-message is-success">{notice}</p>}
        {preview&&<div className="manage-message"><span>پیش‌نمایش خصوصی آماده است؛ ۱۰ دقیقه اعتبار دارد.</span><a href={preview} target="_blank" rel="noopener noreferrer">بازکردن پیش‌نمایش <Icon name="arrow"/></a></div>}
        {tab==='home'&&<div className="manage-overview"><div><span className="manage-overview-icon"><Icon name="grid"/></span><span><strong>{fa(design.sections.length)} بخش</strong><small>چیدمان صفحهٔ اصلی</small></span></div><div><span className="manage-overview-icon"><Icon name="eye"/></span><span><strong>{fa(design.sections.filter(s=>s.enabled!==false).length)} بخش نمایان</strong><small>در پیش‌نویس فعلی</small></span></div><a href="/" target="_blank" rel="noopener"><span className="manage-overview-icon"><Icon name="bag"/></span><span><strong>ویترین فروشگاه شما</strong><small>دیدن نسخهٔ منتشرشده ↗</small></span></a></div>}
        {adding&&tab==='home'&&<section className="manage-add" aria-label="انتخاب نوع بخش"><h2>چه بخشی اضافه کنیم؟</h2><div>{Object.entries(types).map(([type,label])=><button onClick={()=>add(type)} key={type}>{label}<span>+</span></button>)}</div></section>}
        {tab==='home'&&<div className="manage-workbench"><section className="manage-outline" aria-label="بخش‌های صفحه اصلی"><div className="manage-panel-heading"><h2>چیدمان صفحه</h2><small>{fa(design.sections.length)} بخش</small></div><ol>{design.sections.map((s,i)=><li key={i} className={selected===i?'is-selected':''}><button className="manage-section-select" onClick={()=>setSelected(i)} aria-pressed={selected===i}><span className="manage-thumb">{(s.image||s.items?.[0]?.image)?<img src={s.image||s.items[0].image} alt=""/>:<Icon name={s.type==='products'?'bag':s.type==='faq'?'info':'grid'}/>}</span><span><strong>{s.title||types[s.type]}</strong><small>{types[s.type]}{s.enabled===false?' · پنهان':''}</small></span></button><Move index={i} total={design.sections.length} onMove={reorder} label={s.title||types[s.type]}/></li>)}</ol>{!design.sections.length&&<p>هنوز بخشی ندارید. از «افزودن بخش» شروع کنید.</p>}</section>
          <section className="manage-editor" aria-label="ویرایش بخش">{section?<><div className="manage-panel-heading"><h2>{types[section.type]}</h2><Toggle label="نمایش بخش" checked={section.enabled!==false} onChange={value=>setSection({enabled:value})}/></div><fieldset disabled={Boolean(busy)}><SectionEditor key={selected+section.type} value={section} onChange={setSection} onMedia={setMediaTarget}/><details className="manage-details"><summary>چیدمان و نمایش</summary><div className="manage-field-grid"><Select label="نمایش در" value={section.visibility||'all'} onChange={v=>setSection({visibility:v})} options={{all:'همهٔ دستگاه‌ها',desktop:'فقط دسکتاپ',mobile:'فقط موبایل'}}/>{[['columns','ستون دسکتاپ',1,6,4],['mobileColumns','ستون موبایل',1,2,2],['gap','فاصلهٔ آیتم‌ها',8,48,20],['padding','فاصلهٔ داخلی',0,80,0],['spacing','فاصلهٔ بالای بخش',0,80,24]].map(([key,label,min,max,fallback])=><Field key={key} type="number" label={`${label} ${key==='columns'||key==='mobileColumns'?'':'(پیکسل)'}`} min={min} max={max} value={section[key]??fallback} onChange={v=>setSection({[key]:v})}/>)}</div><Field label="رنگ زمینهٔ بخش (اختیاری)" value={section.background} onChange={v=>setSection({background:v})} dir="ltr" placeholder="#ffffff" pattern="#[a-fA-F0-9]{6}"/></details></fieldset><div className="manage-editor-footer"><button disabled={Boolean(busy)||design.sections.length>=40} onClick={()=>{update({...design,sections:[...design.sections,copy(section)]});setSelected(design.sections.length);}}>تکثیر بخش</button><button className="manage-danger" disabled={Boolean(busy)} onClick={remove}>حذف بخش</button></div></>:<div className="manage-empty"><Icon name="grid"/><h2>صفحه‌تان را بسازید</h2><p>یک بخش اضافه کنید تا تنظیمات آن اینجا نمایش داده شود.</p><button onClick={()=>setAdding(true)}>افزودن اولین بخش</button></div>}</section>
          <MiniPreview design={design}/>
        </div>}
        {tab==='identity'&&<section className="manage-settings"><Settings value={design.settings} onChange={setSettings} onMedia={setMediaTarget}/></section>}
        {tab==='presets'&&<PresetGallery onSelect={selectPreset}/>}
        <div hidden={tab!=='connection'}><ConnectionPlanner/></div>
        {tab==='menus'&&<section className="manage-settings">{[['headerLinks','منوی بالای فروشگاه',12],['footerLinks','منوی پایین فروشگاه',36],['mobileLinks','دسترسی سریع موبایل',5]].map(([key,title,max])=><Links key={key} title={title} kind={key} value={design.settings[key]} max={max} onChange={v=>setSettings({[key]:v})}/>)}</section>}
        {(tab==='content'||tab==='display')&&<section className="manage-settings"><fieldset disabled={Boolean(busy)}><ContentSettings mode={tab} value={design.settings} onChange={setSettings}/></fieldset></section>}
        {tab==='history'&&<section className="manage-settings"><h2>نسخه‌های ذخیره‌شده</h2><p>با بازگردانی یک نسخه، تنظیمات و چیدمان همان نسخه منتشر می‌شود. محصولات و سفارش‌ها تغییر نمی‌کنند.</p>{busy==='history'?<p role="status">در حال دریافت تاریخچه…</p>:history.length?<ol className="manage-history">{history.map((r,i)=><li key={r.id}><Icon name="order"/><div><strong>نسخهٔ {fa(history.length-i)}</strong><small>{new Date(`${r.date.replace(' ','T')}Z`).toLocaleString('fa-IR')}</small></div><button disabled={Boolean(busy)} onClick={()=>restore(r.id)}>بازگردانی این نسخه</button></li>)}</ol>:<p>پس از اولین تغییر، نسخه‌های قبلی اینجا نمایش داده می‌شوند.</p>}</section>}
        {tab==='help'&&<section className="manage-settings manage-help"><h2>از انتخاب یک بخش شروع کنید</h2><p>در صفحهٔ اصلی، بخشی مثل اسلایدر یا ویترین محصولات را انتخاب کنید. محتوای آن در ستون ویرایش باز می‌شود. دکمه‌های بالا و پایین ترتیب بخش‌ها را عوض می‌کنند.</p><h2>پیش‌نمایش با انتشار فرق دارد</h2><p>پیش‌نمایش فقط برای شماست. تا «انتشار تغییرات» را نزنید، مشتریان طراحی قبلی را می‌بینند. لینک پیش‌نمایش را در اختیار دیگران نگذارید.</p><h2>اگر از نتیجه راضی نبودید</h2><p>در تاریخچه، یکی از نسخه‌های قبلی را بازگردانید. تغییرات قالب به سفارش‌ها، موجودی و اطلاعات مشتریان دست نمی‌زند.</p><h2>محصولات و عملیات فروشگاه</h2><p>برای مدیریت محصولات، تنوع‌ها، موجودی، سفارش‌ها، تخفیف، روش‌های ارسال و درگاه‌های نصب‌شده، بخش «محصولات و عملیات فروشگاه» را باز کنید. قابلیت‌هایی مثل بازپرداخت و مدیریت کاربران هنوز در این پنل نیستند.</p></section>}
      </main></div>
    <MediaDialog target={mediaTarget} onClose={()=>setMediaTarget(null)}/>
    {reauth&&<Reauthenticate onClose={()=>setReauth(false)}/>}
  </div>;
}
function Reauthenticate({onClose}){
  const dialog=useRef(null);
  useEffect(()=>{dialog.current.showModal();},[]);
  return <dialog ref={dialog} className="manage-reauth" onCancel={onClose}><button onClick={onClose} type="button">بستن؛ تغییرات حفظ می‌شوند</button><Login onLogin={onClose}/></dialog>;
}
export function Login({onLogin}){
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[visible,setVisible]=useState(false);
  async function submit(event){event.preventDefault();const data=new FormData(event.currentTarget);setBusy(true);setError('');try{await api('login',{login:data.get('login'),password:data.get('password')});await onLogin();}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <main className="manage-app manage-login"><a href="/" className="manage-back">بازگشت به فروشگاه <Icon name="arrow"/></a><div className="manage-login-layout"><section className="manage-login-story"><span className="manage-login-mark"><Icon name="bag"/></span><small>استودیوی فروشگاه</small><h2>فروشگاه شما،<br/>با سلیقهٔ شما.</h2><p>از اولین اسلاید تا آخرین سفارش؛ مدیریت فروشگاه در یک فضای ساده و یکپارچه.</p><div className="manage-story-stack"><div><Icon name="grid"/><span>ظاهر و محتوای فروشگاه</span><Icon name="check"/></div><div><Icon name="bag"/><span>محصولات و موجودی</span><Icon name="check"/></div><div><Icon name="order"/><span>سفارش‌ها و کدهای تخفیف</span><Icon name="check"/></div></div><span className="manage-story-note">داده‌ها در وردپرس شما می‌مانند.</span></section><div className="manage-login-panel"><Badge variant="brand">مدیریت مستقل فروشگاه</Badge><h1>خوش آمدید</h1><p>با حساب مدیر وردپرس وارد شوید و فروشگاهتان را مدیریت کنید.</p><form onSubmit={submit}><label className="manage-field"><span>نام کاربری یا ایمیل مدیر</span><input name="login" autoComplete="username" required maxLength={254} dir="auto"/></label><label className="manage-field"><span>رمز عبور</span><span className="manage-password"><input name="password" type={visible?'text':'password'} autoComplete="current-password" required maxLength={1024} dir="ltr"/><button type="button" onClick={()=>setVisible(!visible)} aria-label={visible?'پنهان‌کردن رمز':'نمایش رمز'}><Icon name="eye"/></button></span></label>{error&&<p role="alert" className="manage-message is-error">{error}</p>}<button className="manage-primary" disabled={busy}>{busy?'در حال ورود…':'ورود به مدیریت'}<Icon name="arrow"/></button></form><small>حساب مشتری به مدیریت فروشگاه دسترسی ندارد.</small></div></div></main>;
}
function ImageField({label,value,onChange,onMedia}){return <div className="manage-image-field"><span className="manage-field-label">{label}</span><button type="button" className="manage-image-select" onClick={()=>onMedia({onSelect:onChange})}>{value?<img src={value} alt={label}/>:<span><Icon name="grid"/>انتخاب تصویر</span>}<b>{value?'تغییر تصویر':'از کتابخانه یا رایانه'}</b></button><Field label="نشانی تصویر" value={value} onChange={onChange} type="url" dir="ltr" placeholder="https://…"/>{value&&<button type="button" className="manage-text-button" onClick={()=>onChange('')}>برداشتن تصویر</button>}</div>;}
function SectionEditor({value:s,onChange:set,onMedia}){
  const [itemIndex,setItemIndex]=useState(0);const items=s.items||[];const index=Math.min(itemIndex,Math.max(items.length-1,0));const item=items[index];
  const setItem=changes=>set({items:items.map((v,i)=>i===index?{...v,...changes}:v)});
  return <><Field label="عنوان بخش" value={s.title} onChange={title=>set({title})} maxLength={200}/>
    {['banners','products','categories'].includes(s.type)&&<Select label="سبک ویترین" value={s.presentation||'standard'} onChange={presentation=>set({presentation})} options={s.type==='banners'?{standard:'بنر تصویری',stories:'استوری دایره‌ای',brands:'ردیف برندها',editorial:'کارت تصویر و عنوان'}:s.type==='products'?{standard:'کارت محصول',offers:'ویترین رنگی',spotlight:'محصول منتخب با فهرست',ranked:'فهرست شماره‌دار'}:{standard:'دسته‌بندی ساده',showcase:'ویترین محصولات هر دسته'}}/>}
    {s.type==='products'&&s.presentation==='offers'&&<ImageField label="بنر کنار ویترین" value={s.image} onChange={image=>set({image})} onMedia={onMedia}/>}
    {s.type==='products'&&s.presentation==='standard'&&<Toggle label="محصول منتخب کنار ویترین" checked={Boolean(s.featuredProduct)} onChange={featuredProduct=>set({featuredProduct})}/>}
    {s.type==='hero'&&<><Toggle label="نمایش محصول منتخب کنار اسلایدر" checked={Boolean(s.featuredProduct)} onChange={featuredProduct=>set({featuredProduct})}/>{s.featuredProduct&&<><Select label="جای اسلایدر" value={s.imageSide||'right'} onChange={imageSide=>set({imageSide})} options={{right:'راست',left:'چپ'}}/><CatalogPicker kind="product" selected={s.productIds||[]} onChange={ids=>set({productIds:ids.slice(-1)})}/></>}</>}{['hero','banners','features','faq'].includes(s.type)&&<><div className="manage-items" aria-label="آیتم‌های بخش">{items.map((v,i)=><button key={i} type="button" aria-pressed={i===index} onClick={()=>setItemIndex(i)}>{v.image?<img src={v.image} alt=""/>:<span>{fa(i+1)}</span>}<small>{v.title||`آیتم ${fa(i+1)}`}</small></button>)}<button type="button" disabled={items.length>=20} onClick={()=>{set({items:[...items,{title:'',body:'',image:'',href:'',icon:'info'}]});setItemIndex(items.length);}}><span>+</span><small>{s.type==='hero'?'افزودن اسلاید':s.type==='faq'?'افزودن پرسش':'افزودن آیتم'}</small></button></div>{item?<div className="manage-item-editor">{['hero','banners'].includes(s.type)&&<ImageField label="تصویر" value={item.image} onChange={image=>setItem({image})} onMedia={onMedia}/>}<Field label={s.type==='faq'?'پرسش':'عنوان'} value={item.title} maxLength={200} onChange={title=>setItem({title})}/><Field label={s.type==='faq'?'پاسخ':'توضیح کوتاه'} multiline value={item.body} maxLength={2000} onChange={body=>setItem({body})}/>{s.type!=='faq'&&<Field label="پیوند" value={item.href} dir="ltr" onChange={href=>setItem({href})} hint="مسیر داخل فروشگاه مثل /shop یا نشانی کامل HTTPS"/>}{s.type==='features'&&<Select label="نماد" value={item.icon||'info'} onChange={icon=>setItem({icon})} options={{info:'اطلاعات',check:'تأیید',bag:'سبد',user:'حساب',heart:'علاقه‌مندی',pin:'نشانی',order:'سفارش',home:'خانه',grid:'فهرست'}}/>}<div className="manage-item-actions"><Move label="آیتم" index={index} total={items.length} onMove={(i,d)=>{set({items:move(items,i,d)});setItemIndex(i+d);}}/><button type="button" className="manage-danger" onClick={()=>{set({items:items.filter((_,i)=>i!==index)});setItemIndex(Math.max(0,index-1));}}>حذف این {s.type==='hero'?'اسلاید':s.type==='faq'?'پرسش':'آیتم'}</button></div></div>:<p className="manage-hint">برای شروع یک {s.type==='hero'?'اسلاید':'آیتم'} اضافه کنید.</p>}</>}
{s.type==='products'&&<><div className="manage-field-grid"><Select label="منبع محصولات" value={s.source||'all'} onChange={source=>set({source})} options={{all:'همهٔ محصولات',category:'یک دسته‌بندی',manual:'انتخاب دستی'}}/><Select label="مرتب‌سازی" value={s.sort||'newest'} onChange={sort=>set({sort})} options={{newest:'جدیدترین',cheap:'ارزان‌ترین',expensive:'گران‌ترین'}}/><Select label="نوع نمایش" value={s.display||'grid'} onChange={display=>set({display})} options={{grid:'شبکه‌ای',carousel:'ردیف اسکرولی'}}/><Field label="تعداد کالا" type="number" min={1} max={100} value={s.limit??12} onChange={limit=>set({limit})}/></div>{s.source==='category'&&<CatalogPicker kind="category" selected={s.categoryId?[s.categoryId]:[]} onChange={ids=>set({categoryId:ids.at(-1)||0})}/>} {s.source==='manual'&&<CatalogPicker kind="product" selected={s.productIds||[]} onChange={productIds=>set({productIds})}/>}{!['spotlight','ranked'].includes(s.presentation)&&<Toggle label="نمایش فیلترها برای خریدار" checked={Boolean(s.showFilters)} onChange={showFilters=>set({showFilters})}/>}</>}
    {s.type==='categories'&&<CatalogPicker kind="category" selected={s.categoryIds||[]} onChange={categoryIds=>set({categoryIds})}/>}
    {s.type==='text-image'&&<><ImageField label="تصویر بخش" value={s.image} onChange={image=>set({image})} onMedia={onMedia}/><Field label="عنوان کوتاه بالای متن" value={s.subtitle} onChange={subtitle=>set({subtitle})}/><Field label="متن" value={s.body} multiline maxLength={5000} onChange={body=>set({body})}/><div className="manage-field-grid"><Field label="عنوان دکمه" value={s.buttonLabel} onChange={buttonLabel=>set({buttonLabel})}/><Field label="پیوند دکمه" value={s.href} dir="ltr" onChange={href=>set({href})}/></div><Select label="جای تصویر" value={s.imageSide||'right'} onChange={imageSide=>set({imageSide})} options={{right:'راست',left:'چپ'}}/></>}
    {s.type==='spacer'&&<p className="manage-hint">ارتفاع فضای خالی را از «فاصلهٔ داخلی» در تنظیمات چیدمان تغییر دهید.</p>}
  </>;
}
function Settings({value:s,onChange:set,onMedia}){return <><h2>هویت فروشگاه</h2><Select label="سبک ویترین" value={s.theme||'craft'} onChange={theme=>set({theme})} options={{craft:'صنایع‌دستی',digital:'دیجیتال',grocery:'خرید روزمره'}}/><div className="manage-field-grid"><Field label="نام فروشگاه" value={s.name} onChange={name=>set({name})} maxLength={200}/><Field label="توضیح کوتاه زیر نام" value={s.tagline} onChange={tagline=>set({tagline})}/></div><Field label="توضیحات فروشگاه" value={s.description} onChange={description=>set({description})}/><div className="manage-field-grid"><ImageField label="لوگو" value={s.logo} onChange={logo=>set({logo})} onMedia={onMedia}/><ImageField label="نماد مرورگر" value={s.favicon} onChange={favicon=>set({favicon})} onMedia={onMedia}/></div><h2>رنگ‌ها</h2><div className="manage-colors">{[['primary','رنگ اصلی'],['background','زمینه'],['surface','سطح محتوا'],['text','متن'],['muted','متن فرعی']].map(([key,label])=><label key={key}><input type="color" aria-label={label} value={s[key]} onChange={e=>set({[key]:e.target.value})}/><span>{label}<small dir="ltr">{s[key]}</small></span></label>)}</div><h2>فونت و ابعاد</h2><div className="manage-field-grid"><Select label="فونت" value={s.font} onChange={font=>set({font})} options={{system:'فونت فعلی قالب',tahoma:'Tahoma',custom:'فونت اختصاصی'}}/><Field label="اندازهٔ متن (پیکسل)" type="number" min={12} max={20} value={s.fontSize} onChange={fontSize=>set({fontSize})}/><Field label="عرض محتوا (پیکسل)" type="number" min={960} max={1440} value={s.containerWidth} onChange={containerWidth=>set({containerWidth})}/></div>{s.font==='custom'&&<Field label="نشانی فایل فونت WOFF یا WOFF2" type="url" dir="ltr" value={s.fontUrl} onChange={fontUrl=>set({fontUrl})} hint="فقط فونتی که مجوز استفاده‌اش را دارید. فایل باید از HTTPS در دسترس باشد."/>}<h2>اعلان و پایین صفحه</h2>{[['announcement','متن نوار اعلان'],['announcementNote','متن فرعی اعلان'],['footerText','توضیح پایین صفحه'],['footerNote','یادداشت پایین فروشگاه']].map(([key,label])=><Field key={key} label={label} value={s[key]} onChange={v=>set({[key]:v})} multiline={key==='footerText'}/>)}<details className="manage-details"><summary>تنظیمات اتصال</summary><Field label="نشانی اصلی فرانت‌اند" value={s.frontendUrl} onChange={frontendUrl=>set({frontendUrl})} type="url" dir="ltr" hint="نشانی HTTPS فروشگاه بدون مسیر اضافه؛ برای پیش‌نمایش خصوصی استفاده می‌شود."/></details></>;}
function Links({title,kind,value,max,onChange}){return <section className="manage-links"><h2>{title}</h2>{value.map((link,index)=><div className="manage-link-row" key={index}><Field label="عنوان" value={link.label} onChange={v=>onChange(value.map((l,i)=>i===index?{...l,label:v}:l))}/><Field label="پیوند" dir="ltr" value={link.href} onChange={v=>onChange(value.map((l,i)=>i===index?{...l,href:v}:l))}/>{kind==='footerLinks'&&<Field label="گروه" value={link.group} onChange={v=>onChange(value.map((l,i)=>i===index?{...l,group:v}:l))}/>} {kind==='mobileLinks'&&<Select label="نماد" value={link.icon} onChange={v=>onChange(value.map((l,i)=>i===index?{...l,icon:v}:l))} options={{home:'خانه',grid:'فهرست',heart:'علاقه‌مندی',bag:'سبد',user:'حساب',info:'اطلاعات',search:'جست‌وجو',order:'سفارش'}}/>}<Move label={link.label||'پیوند'} index={index} total={value.length} onMove={(i,d)=>onChange(move(value,i,d))}/><button className="manage-danger" onClick={()=>onChange(value.filter((_,i)=>i!==index))} aria-label={`حذف پیوند ${link.label}`}>حذف</button></div>)}<button disabled={value.length>=max} onClick={()=>onChange([...value,{label:'',href:'',group:'',icon:'info'}])}>+ افزودن پیوند</button><small className="manage-hint">حداکثر {fa(max)} پیوند</small></section>;}
function CatalogPicker({kind,selected,onChange}){const [search,setSearch]=useState(''),[items,setItems]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(false);useEffect(()=>{let active=true;const timer=setTimeout(()=>{setLoading(true);api('catalog',{kind,search}).then(r=>{if(active){setItems(r.items);setError('');}}).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));},300);return()=>{active=false;clearTimeout(timer);};},[search,kind]);return <div className="manage-picker"><Field label={kind==='category'?'جست‌وجوی دسته‌بندی':'جست‌وجوی محصول'} value={search} onChange={setSearch}/>{error&&<p role="alert">{error}</p>}<small>{fa(selected.length)} انتخاب شده {selected.length>0&&<button type="button" onClick={()=>onChange([])}>پاک‌کردن انتخاب‌ها</button>}</small>{loading?<p role="status">در حال دریافت…</p>:<div>{items.map(item=><label key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={e=>onChange(e.target.checked?[...selected,item.id]:selected.filter(id=>id!==item.id))}/>{item.name}</label>)}{!items.length&&<p>نتیجه‌ای پیدا نشد.</p>}</div>}</div>;}
function MiniPreview({design}){return <aside className="manage-preview"><h2>مرور چیدمان</h2><p>نمای خلاصه؛ نتیجهٔ دقیق در پیش‌نمایش</p><div className="manage-phone" style={{background:design.settings.background,color:design.settings.text}}><div className="manage-phone-head" style={{background:design.settings.surface}}>{design.settings.logo?<img src={design.settings.logo} alt=""/>:<b>{design.settings.name}</b>}<Icon name="bag"/></div>{design.sections.filter(s=>s.enabled!==false&&s.visibility!=='desktop').map((s,i)=><div className="manage-phone-section" key={i}>{(s.image||s.items?.[0]?.image)&&<img src={s.image||s.items[0].image} alt=""/>}<span>{s.title||types[s.type]}</span></div>)}</div></aside>;}
export function MediaDialog({target,onClose}){
  const dialog=useRef(null),[items,setItems]=useState([]),[search,setSearch]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{if(target){dialog.current.showModal();setSearch('');}else dialog.current?.close();},[target]);
  useEffect(()=>{if(!target)return;let active=true;const timer=setTimeout(()=>{setBusy(true);api('media',{search}).then(r=>{if(active){setItems(r.items);setError('');}}).catch(e=>active&&setError(e.message)).finally(()=>active&&setBusy(false));},250);return()=>{active=false;clearTimeout(timer);};},[target,search]);
  async function upload(event){const file=event.target.files[0];if(!file)return;if(file.size>5*1024*1024){setError('حجم تصویر باید کمتر از ۵ مگابایت باشد.');return;}setBusy(true);setError('');try{const form=new FormData();form.append('file',file);const item=await api('upload',form);(target.onSelectItem?target.onSelectItem(item):target.onSelect(item.url));onClose();}catch(e){setError(e.message);}finally{setBusy(false);event.target.value='';}}
  return <dialog ref={dialog} className="manage-media" aria-labelledby="manage-media-title" onCancel={onClose}><div className="manage-panel-heading"><h2 id="manage-media-title">انتخاب تصویر</h2><button onClick={onClose} aria-label="بستن انتخاب تصویر"><Icon name="close"/></button></div><Field label="جست‌وجو در کتابخانه" value={search} onChange={setSearch}/><label className="manage-upload">بارگذاری تصویر تازه<input type="file" accept="image/jpeg,image/png,image/webp" onChange={upload} disabled={busy}/><small>JPEG، PNG یا WebP، تا ۵ مگابایت</small></label>{error&&<p role="alert" className="manage-message is-error">{error}</p>}{busy?<p role="status">در حال دریافت تصاویر…</p>:<div className="manage-media-grid">{items.map(item=><button key={item.id} onClick={()=>{(target.onSelectItem?target.onSelectItem(item):target.onSelect(item.url));onClose();}}><img src={item.thumbnail} alt=""/><span>{item.title||'تصویر بدون عنوان'}</span></button>)}{!items.length&&<p>تصویری پیدا نشد. یک تصویر بارگذاری کنید.</p>}</div>}</dialog>;
}
