'use client';
// Operate: inherit the merchant studio; show the order facts, then the next safe action.
import {useEffect,useState} from 'react';
import Icon from '../../components/icons';
import {IRAN_STATES} from '../../../lib/iran-states';
import {Badge} from '../../components/vibefarsi/controls';
import {customerName,orderStatuses,orderStatusOptions,money,dateLabel,text} from '../../../lib/customer-orders';

function Address({value={},title}){return <section className="operations-address"><h3>{title}</h3><strong>{[value.first_name,value.last_name].filter(Boolean).join(' ')||'نام ثبت نشده'}</strong><p>{[value.company,value.address_1,value.address_2,value.city,value.country==='IR'?(IRAN_STATES[value.state]||value.state):value.state,value.country==='IR'?'ایران':value.country].filter(Boolean).join('، ')||'نشانی ثبت نشده است.'}</p>{value.postcode&&<small>کد پستی: <bdi>{value.postcode}</bdi></small>}{value.phone&&<a dir="ltr" href={'tel:'+value.phone}>{value.phone}</a>}{value.email&&<a dir="ltr" href={'mailto:'+value.email}>{value.email}</a>}</section>;}
export function OrderEditor({item,value,onChange,Field,call,onSaveNote,noteRefresh,onNoteDraftChange,busy,dirty,unresolved,onOpenCustomer}){
 const currency=item.currency;
 return <div className="operations-order"><div className="operations-order-heading"><div><Badge variant={item.status==='completed'?'success':item.status==='failed'?'warning':'brand'}>{orderStatuses[item.status]||item.status}</Badge><p>ثبت سفارش: {dateLabel(item.date_created_gmt)}</p></div><strong>{money(item.total,currency)}</strong></div>
 <div className="operations-order-grid"><div><h2>اقلام سفارش</h2><div className="operations-items">{item.line_items?.map(line=><div key={line.id}>{line.image?.src&&<img src={line.image.src} alt="" loading="lazy"/>}<div><strong>{text(line.name)}</strong><small>تعداد: {Number(line.quantity).toLocaleString('fa-IR')}</small>{line.sku&&<small>شناسه: <bdi>{line.sku}</bdi></small>}</div><strong>{money(line.total,currency)}</strong></div>)}</div>
 <div className="operations-addresses"><Address title="صورت‌حساب" value={item.billing}/><Address title="تحویل سفارش" value={item.shipping}/></div>
 <section className="operations-notes"><h2>یادداشت‌های سفارش</h2><OrderNotes key={item.id} id={item.id} onDraftChange={onNoteDraftChange} call={call} onSave={onSaveNote} refresh={noteRefresh} disabled={busy||dirty||Boolean(unresolved)}/>{dirty&&<p className="manage-hint">پیش از افزودن یادداشت، تغییرات سفارش را ذخیره کنید.</p>}</section></div>
 <aside className="operations-summary"><h2>خلاصه و اقدام</h2><dl><div><dt>مجموع اقلام</dt><dd>{money((item.line_items||[]).reduce((sum,l)=>sum+Number(l.subtotal||0),0),currency)}</dd></div><div><dt>تخفیف</dt><dd>{money(item.discount_total,currency)}</dd></div><div><dt>ارسال</dt><dd>{money(item.shipping_total,currency)}</dd></div><div><dt>مالیات</dt><dd>{money(item.total_tax,currency)}</dd></div><div><dt>مبلغ نهایی</dt><dd>{money(item.total,currency)}</dd></div></dl>{item.coupon_lines?.length>0&&<p>کد تخفیف: {item.coupon_lines.map(c=>c.code).join('، ')}</p>}<p>روش پرداخت: {text(item.payment_method_title)||'ثبت نشده'}</p>{item.transaction_id&&<p>شناسهٔ تراکنش: <bdi>{item.transaction_id}</bdi></p>}{item.date_paid_gmt&&<p>زمان ثبت پرداخت: {dateLabel(item.date_paid_gmt)}</p>}{item.shipping_lines?.map(line=><p key={line.id}>روش دریافت: {text(line.method_title)}</p>)}
 <Field label="وضعیت سفارش" value={value.status} options={orderStatusOptions(item)} onChange={status=>onChange({status})}/><Field label="یادداشت سفارش برای مشتری" value={value.customer_note} large onChange={customer_note=>onChange({customer_note})}/><p className="manage-hint">تغییر وضعیت می‌تواند ایمیل یا موجودی را تغییر دهد. این بخش بازپرداخت انجام نمی‌دهد و پرداخت آنلاین تأییدنشده را قطعی نمی‌کند.</p>{item.customer_id>0?<button type="button" onClick={()=>onOpenCustomer(item.customer_id)}><Icon name="user"/>پروندهٔ مشتری</button>:<p className="manage-hint">خرید مهمان؛ حساب مشتری به این سفارش متصل نیست.</p>}</aside></div></div>;
}
function OrderNotes({id,call,onSave,refresh,disabled,onDraftChange}){
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[note,setNote]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{onDraftChange(Boolean(note.trim()));return()=>onDraftChange(false);},[note,onDraftChange]);
 useEffect(()=>{let active=true;setLoading(true);setError('');call({resource:'order-notes',parentId:id,verb:'list'}).then(r=>{if(active)setItems(r.items);}).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false;};},[id,refresh,retry,call]);
 return <>{error&&<div role="alert"><p>{error}</p><button type="button" onClick={()=>setRetry(n=>n+1)}>دریافت دوبارهٔ یادداشت‌ها</button></div>}{loading?<p role="status">در حال دریافت یادداشت‌ها…</p>:<ol className="operations-timeline">{items.map(n=><li key={n.id}><Badge variant={n.customer_note?'brand':'default'}>{n.customer_note?'قابل مشاهده برای مشتری':'یادداشت داخلی'}</Badge><time>{dateLabel(n.date_created_gmt)}</time><p>{text(n.note)}</p></li>)}</ol>}{!loading&&!error&&!items.length&&<p className="manage-hint">هنوز یادداشتی ثبت نشده است. برای ثبت هماهنگی‌ها، یادداشت داخلی اضافه کنید.</p>}<label className="manage-field"><span>یادداشت داخلی تازه</span><textarea rows={3} maxLength={5000} value={note} onChange={e=>setNote(e.target.value)} disabled={disabled}/><small>فقط مدیر فروشگاه می‌بیند؛ برای مشتری پیام یا ایمیل ارسال نمی‌شود.</small></label><button type="button" disabled={disabled||!note.trim()} onClick={async()=>{if(await onSave(note))setNote('');}}>ثبت یادداشت داخلی</button></>;
}
export function CustomerEditor({item,value,onChange,Field,onViewOrders}){
 const fields={first_name:'نام',last_name:'نام خانوادگی',company:'شرکت (اختیاری)',country:'کشور (کد دوحرفی)',state:'استان',city:'شهر',address_1:'نشانی',address_2:'ادامهٔ نشانی',postcode:'کد پستی',email:'ایمیل صورت‌حساب',phone:'شمارهٔ تماس'};
 return <div className="operations-customer"><div className="operations-profile"><span className="operations-avatar"><Icon name="user"/></span><div><h2>{customerName(item)}</h2><p dir="ltr">{item.email}</p><small>عضویت: {dateLabel(item.date_created_gmt||item.date_created)}</small></div><button type="button" onClick={()=>onViewOrders(item.id)}><Icon name="order"/>سفارش‌های این مشتری</button></div><p className="manage-hint">اطلاعات تماس و نشانی در حساب مشتری ذخیره می‌شوند؛ سفارش‌های قبلی تغییر نمی‌کنند. ایمیل ورود، رمز و سطح دسترسی از این بخش تغییر نمی‌کنند.</p><div className="manage-field-grid"><Field label="نام مشتری" value={value.first_name} onChange={first_name=>onChange({first_name})}/><Field label="نام خانوادگی مشتری" value={value.last_name} onChange={last_name=>onChange({last_name})}/></div>{['billing','shipping'].map(kind=><section className="operations-customer-address" key={kind}><h2>{kind==='billing'?'اطلاعات صورت‌حساب':'نشانی دریافت سفارش'}</h2><div className="manage-field-grid">{Object.entries(value[kind]).map(([key,v])=><Field key={key} label={fields[key]} value={v} type={key==='email'?'email':'text'} options={key==='state'&&value[kind].country==='IR'?{'':'انتخاب استان',...IRAN_STATES,...(v&&!IRAN_STATES[v]?{[v]:v}:{})}:undefined} onChange={text=>onChange({[kind]:{...value[kind],[key]:text}})}/>)}</div></section>)}</div>;
}
