(function(wp){
  'use strict';
  const h=wp.element.createElement, Fragment=wp.element.Fragment, {useState,useEffect}=wp.element;
  const {TextControl,TextareaControl,ToggleControl,SelectControl,RangeControl,PanelBody,Button,Notice,CheckboxControl}=wp.components;
  const {InspectorControls,MediaUpload,MediaUploadCheck,useBlockProps}=wp.blockEditor;
  const defaults=window.PaastaBuilder.defaults;
  const labels={'site-settings':'تنظیمات کلی فروشگاه',hero:'اسلایدر تصویری',banners:'بنرهای تصویری',categories:'دسته‌بندی محصولات',products:'ویترین محصولات','text-image':'تصویر و متن',features:'خدمات فروشگاه',faq:'سؤالات متداول',spacer:'فاصله‌گذار'};
  const iconOptions=[['info','اطلاعات'],['home','خانه'],['grid','دسته‌بندی'],['heart','علاقه‌مندی'],['bag','سبد'],['user','حساب'],['check','تأیید'],['order','سفارش'],['pin','نشانی'],['search','جست‌وجو']].map(([value,label])=>({value,label}));
  const choice=(label,value,onChange,options)=>h(SelectControl,{label,value,onChange,options:options.map(([value,label])=>({value,label}))});
  function Media({label,value,onChange,font=false}){return h('div',{className:'phb-media'},h('strong',null,label),!font&&value&&h('img',{src:value,alt:'',loading:'lazy'}),h(MediaUploadCheck,null,h(MediaUpload,{allowedTypes:font?['font/woff','font/woff2']:['image'],value:undefined,onSelect:media=>onChange(media.url),render:({open})=>h(Button,{variant:'secondary',onClick:open},font?'انتخاب فایل فونت':'انتخاب از رسانه‌ها')})),h(TextControl,{label:font?'نشانی HTTPS فایل WOFF یا WOFF2':'نشانی HTTPS تصویر',value:value||'',onChange,dir:'ltr'}),value&&h(Button,{variant:'tertiary',isDestructive:true,onClick:()=>onChange('')},'برداشتن فایل'));}
  function Items({value=[],onChange,fields,max=20,label='آیتم'}){
    function update(index,key,next){onChange(value.map((item,i)=>i===index?{...item,[key]:next}:item));}
    function move(index,step){const next=[...value];[next[index],next[index+step]]=[next[index+step],next[index]];onChange(next);}
    return h('div',{className:'phb-items'},value.map((item,index)=>h(PanelBody,{key:index,title:`${label} ${(index+1).toLocaleString('fa-IR')}: ${item.title||item.label||'بدون عنوان'}`,initialOpen:false},fields.map(([key,title,kind])=>h(Fragment,{key},kind==='image'?h(Media,{label:title,value:item[key],onChange:next=>update(index,key,next)}):kind==='icon'?h(SelectControl,{label:title,value:item[key]||'info',options:iconOptions,onChange:next=>update(index,key,next)}):h(kind==='body'?TextareaControl:TextControl,{label:title,value:item[key]||'',onChange:next=>update(index,key,next),...(kind==='url'?{dir:'ltr'}:{})}))),h('div',{className:'phb-actions'},h(Button,{variant:'secondary',disabled:index===0,onClick:()=>move(index,-1)},'بالا'),h(Button,{variant:'secondary',disabled:index===value.length-1,onClick:()=>move(index,1)},'پایین'),h(Button,{isDestructive:true,variant:'tertiary',onClick:()=>onChange(value.filter((_,i)=>i!==index))},'حذف')))),h(Button,{variant:'secondary',disabled:value.length>=max,onClick:()=>onChange([...value,{}])},'افزودن '+label));
  }
  function CatalogPicker({kind,value,onChange,multiple=false}){
    const [query,setQuery]=useState(''),[items,setItems]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
    useEffect(()=>{let active=true;const timer=setTimeout(()=>{setBusy(true);wp.apiFetch({path:'/wc/store/v1/products'+(kind==='category'?'/categories':'')+'?per_page=100&search='+encodeURIComponent(query)}).then(data=>{if(active){setItems(Array.isArray(data)?data:[]);setError('');}}).catch(()=>{if(active)setError('فهرست دریافت نشد؛ جست‌وجو را دوباره تغییر دهید.');}).finally(()=>{if(active)setBusy(false);});},300);return()=>{active=false;clearTimeout(timer);};},[query,kind]);
    const selected=multiple?(value||[]):value?[value]:[];
    return h('div',{className:'phb-picker'},h(TextControl,{label:kind==='category'?'جست‌وجوی دسته‌بندی':'جست‌وجوی محصول',value:query,onChange:setQuery}),busy&&h('p',{role:'status'},'در حال دریافت…'),error&&h(Notice,{status:'error',isDismissible:false},error),h('div',{className:'phb-selected'},selected.map(id=>h(Button,{key:id,variant:'secondary',onClick:()=>onChange(multiple?selected.filter(item=>item!==id):0)},(items.find(item=>item.id===id)?.name||'#'+id)+' ×'))),h('div',{className:'phb-picker-results'},items.map(item=>h(CheckboxControl,{key:item.id,label:item.name,checked:selected.includes(item.id),onChange:checked=>onChange(multiple?(checked?[...new Set([...selected,item.id])]:selected.filter(id=>id!==item.id)):(checked?item.id:0))}))),h('small',null,'حداکثر ۱۰۰ نتیجه در هر جست‌وجو؛ انتخاب‌ها فقط از کاتالوگ متصل در فرانت‌اند نمایش داده می‌شوند.'));
  }
  function Settings({value,set}){return h(Fragment,null,
    h(PanelBody,{title:'هویت و اتصال',initialOpen:true},h(TextControl,{label:'نام فروشگاه',value:value.name||'',onChange:name=>set({name})}),h(TextControl,{label:'توضیح کوتاه زیر نام',value:value.tagline||'',onChange:tagline=>set({tagline})}),h(TextareaControl,{label:'توضیحات فروشگاه',value:value.description||'',onChange:description=>set({description})}),h(TextControl,{label:'نشانی HTTPS فرانت‌اند',help:'فقط دامنهٔ خود فروشگاه؛ برای پیش‌نمایش امن لازم است. بدون مسیر یا پارامتر.',value:value.frontendUrl||'',onChange:frontendUrl=>set({frontendUrl}),dir:'ltr'}),h(Media,{label:'لوگو',value:value.logo,onChange:logo=>set({logo})}),h(Media,{label:'فاوآیکن',value:value.favicon,onChange:favicon=>set({favicon})})),
    h(PanelBody,{title:'رنگ‌ها و ابعاد',initialOpen:false},[['primary','رنگ اصلی'],['background','پس‌زمینه'],['surface','سطح کارت‌ها'],['text','متن'],['muted','متن فرعی']].map(([key,label])=>h(TextControl,{key,label,type:'color',value:value[key]||defaults.settings[key],onChange:color=>set({[key]:color})})),h(RangeControl,{label:'عرض محتوا در دسکتاپ',value:value.containerWidth||1240,min:960,max:1440,step:20,onChange:containerWidth=>set({containerWidth})})),
    h(PanelBody,{title:'فونت',initialOpen:false},choice('خانوادهٔ فونت',value.font||'system',font=>set({font}),[['system','یکان‌بخ موجود روی دستگاه / فونت جایگزین'],['tahoma','Tahoma'],['custom','فونت اختصاصی']]),value.font==='custom'&&h(Media,{font:true,label:'فونت دارای مجوز',value:value.fontUrl,onChange:fontUrl=>set({fontUrl})}),h('p',null,'فایل فونت باید مجوز استفاده داشته باشد. برای فونت روی دامنهٔ دیگر، CORS آن میزبان باید اجازهٔ بارگذاری بدهد.'),h(RangeControl,{label:'اندازهٔ پایهٔ نوشته‌ها',value:value.fontSize||14,min:12,max:20,onChange:fontSize=>set({fontSize})})),
    h(PanelBody,{title:'نوار اعلان و پابرگ',initialOpen:false},[['announcement','متن نوار اعلان'],['announcementNote','متن فرعی اعلان'],['footerText','توضیح پابرگ'],['footerNote','یادداشت پایین فروشگاه']].map(([key,label])=>h(TextareaControl,{key,label,value:value[key]||'',onChange:text=>set({[key]:text})}))),
    [['headerLinks','منوی هدر',12],['footerLinks','منوی پابرگ',36],['mobileLinks','منوی موبایل',5]].map(([key,title,max])=>h(PanelBody,{key,title,initialOpen:false},h(Items,{value:value[key]||[],max,label:'پیوند',onChange:items=>set({[key]:items}),fields:[['label','عنوان'],['href','نشانی','url'],...(key==='footerLinks'?[['group','عنوان ستون']]:[]),...(key==='mobileLinks'?[['icon','آیکن','icon']]:[])]})))
  );}
  function Edit({attributes,setAttributes},type){
    const base=type==='site-settings'?defaults.settings:defaults.sections.find(section=>section.type===type)||{};
    useEffect(()=>{if(!attributes.values||!Object.keys(attributes.values).length)setAttributes({values:{title:labels[type],...base}});},[]);
    const value={...base,...attributes.values};const set=patch=>setAttributes({values:{...value,...patch}});
    const props=useBlockProps({className:'phb-block'+(value.enabled===false?' phb-disabled':'')});
    const common=type==='site-settings'?null:h(PanelBody,{title:'چیدمان و نمایش',initialOpen:false},h(ToggleControl,{label:'نمایش سکشن',checked:value.enabled!==false,onChange:enabled=>set({enabled})}),choice('نمایش در دستگاه‌ها',value.visibility||'all',visibility=>set({visibility}),[['all','همهٔ دستگاه‌ها'],['desktop','فقط دسکتاپ'],['mobile','فقط موبایل']]),h(RangeControl,{label:'ستون‌های دسکتاپ',value:value.columns||4,min:1,max:6,onChange:columns=>set({columns})}),h(RangeControl,{label:'ستون‌های موبایل',value:value.mobileColumns||2,min:1,max:2,onChange:mobileColumns=>set({mobileColumns})}),h(RangeControl,{label:'فاصلهٔ آیتم‌ها',value:value.gap??20,min:8,max:48,onChange:gap=>set({gap})}),h(RangeControl,{label:'فاصلهٔ داخلی',value:value.padding??0,min:0,max:80,onChange:padding=>set({padding})}),h(RangeControl,{label:'فاصلهٔ بالای سکشن',value:value.spacing??24,min:0,max:80,onChange:spacing=>set({spacing})}),h(TextControl,{label:'رنگ پس‌زمینه (اختیاری، مانند #ffffff)',value:value.background||'',onChange:background=>set({background}),dir:'ltr'}));
    let controls;
    if(type==='site-settings')controls=h(Settings,{value,set});
    else controls=h(Fragment,null,h(TextControl,{label:'عنوان سکشن',value:value.title||'',onChange:title=>set({title})}),
      ['hero','banners','features','faq'].includes(type)&&h(Items,{value:value.items||[],onChange:items=>set({items}),label:type==='hero'?'اسلاید':type==='faq'?'پرسش':'آیتم',fields:[['title',type==='faq'?'پرسش':'عنوان'],...(['hero','banners'].includes(type)?[['image','تصویر','image']]:[]),...(['features','faq'].includes(type)?[['body',type==='faq'?'پاسخ':'توضیح','body']]:[]),...(type!=='faq'?[['href','پیوند','url']]:[]),...(type==='features'?[['icon','آیکن','icon']]:[])]}),
      type==='text-image'&&h(Fragment,null,h(TextControl,{label:'عنوان کوتاه بالای متن',value:value.subtitle||'',onChange:subtitle=>set({subtitle})}),h(TextareaControl,{label:'متن',value:value.body||'',onChange:body=>set({body})}),h(Media,{label:'تصویر',value:value.image,onChange:image=>set({image})}),choice('جای تصویر',value.imageSide||'right',imageSide=>set({imageSide}),[['right','راست'],['left','چپ']]),h(TextControl,{label:'عنوان دکمه',value:value.buttonLabel||'',onChange:buttonLabel=>set({buttonLabel})}),h(TextControl,{label:'پیوند دکمه',value:value.href||'',onChange:href=>set({href}),dir:'ltr'})),
      type==='products'&&h(Fragment,null,choice('منبع محصولات',value.source||'all',source=>set({source}),[['all','همهٔ محصولات'],['category','یک دسته‌بندی'],['manual','انتخاب دستی']]),value.source==='category'&&h(CatalogPicker,{kind:'category',value:value.categoryId,onChange:categoryId=>set({categoryId})}),value.source==='manual'&&h(CatalogPicker,{kind:'product',multiple:true,value:value.productIds,onChange:productIds=>set({productIds})}),choice('مرتب‌سازی',value.sort||'newest',sort=>set({sort}),[['newest','جدیدترین'],['cheap','ارزان‌ترین'],['expensive','گران‌ترین']]),choice('نوع نمایش',value.display||'grid',display=>set({display}),[['grid','شبکه‌ای'],['carousel','ردیف اسکرولی']]),h(RangeControl,{label:'حداکثر تعداد کالا',value:value.limit||12,min:1,max:100,onChange:limit=>set({limit})}),h(ToggleControl,{label:'نمایش فیلترها برای خریدار',checked:value.showFilters===true,onChange:showFilters=>set({showFilters})})),
      type==='categories'&&h(Fragment,null,h('p',null,'بدون انتخاب، همهٔ دسته‌های کاتالوگ نمایش داده می‌شوند.'),h(CatalogPicker,{kind:'category',multiple:true,value:value.categoryIds,onChange:categoryIds=>set({categoryIds})}))
    );
    return h(Fragment,null,h(InspectorControls,null,common),h('div',props,h('div',{className:'phb-heading'},h('strong',null,labels[type]),value.enabled===false&&h('span',null,'مخفی')),type==='site-settings'&&h(Notice,{status:'info',isDismissible:false},'تغییرات این بلوک روی همهٔ صفحات اعمال می‌شود. سکشن‌های پایین را از فهرست بلوک‌ها جابه‌جا، تکثیر یا حذف کنید. برای دیدن نتیجه از «پیش‌نمایش فرانت‌اند» استفاده کنید.'),h('div',{className:'phb-controls'},controls),common&&h('p',{className:'phb-hint'},'ستون‌ها، فاصله‌ها و نمایش موبایل در نوار کناری «بلوک» تنظیم می‌شوند.')));
  }
  Object.keys(labels).forEach(type=>wp.blocks.registerBlockType('paasta/'+type,{apiVersion:3,title:labels[type],category:'paasta-store',icon:type==='site-settings'?'admin-appearance':type==='hero'?'images-alt2':'screenoptions',attributes:{values:{type:'object',default:{}}},supports:{html:false,customClassName:false,multiple:type!=='site-settings'},edit:props=>Edit(props,type),save:()=>null}));
  function PreviewPanel(){
    const [busy,setBusy]=useState(false),[error,setError]=useState(''),[link,setLink]=useState('');
    const postType=wp.data.useSelect(select=>select('core/editor').getCurrentPostType(),[]);
    if(postType!=='paasta_design')return null;
    async function preview(){setBusy(true);setError('');setLink('');try{const result=await wp.apiFetch({path:'/paasta-headless/v1/preview',method:'POST',data:{content:wp.data.select('core/editor').getEditedPostContent()}});setLink(result.url);}catch(cause){setError(cause.message||'پیش‌نمایش ساخته نشد. دوباره تلاش کنید.');}finally{setBusy(false);}}
    return h(wp.editor.PluginDocumentSettingPanel,{name:'paasta-preview',title:'پیش‌نمایش فرانت‌اند'},h('p',null,'پیش از انتشار، نتیجه را در خود فروشگاه ببینید. پیوند خصوصی است و ۱۰ دقیقه اعتبار دارد.'),h(Button,{variant:'secondary',isBusy:busy,disabled:busy,onClick:preview},'ساخت پیش‌نمایش امن'),error&&h(Notice,{status:'error',isDismissible:false},error),link&&h('p',null,h('a',{href:link,target:'_blank',rel:'noopener noreferrer',className:'button button-primary'},'بازکردن پیش‌نمایش فرانت‌اند')),h('p',null,'انتشار و بازگشت به نسخه‌های قبلی از کنترل‌های ذخیره و «رونوشت‌ها»ی خود وردپرس انجام می‌شود.'));
  }
  wp.plugins.registerPlugin('paasta-headless-preview',{render:PreviewPanel});
})(window.wp);
