import StoreLink from '../components/store-link';
import { customerAccount } from '../../lib/customer-session';
import LogoutButton from './view';
import {Breadcrumbs} from '../components/ui';
import AuthFrame from '../components/auth-frame';
import Icon from '../components/icons';
export const metadata = { title: 'حساب من | خانه‌چین', robots:{index:false,follow:false} };
export const dynamic = 'force-dynamic';
const statusLabels={pending:'در انتظار پرداخت',processing:'در حال آماده‌سازی',completed:'تکمیل‌شده','on-hold':'در انتظار بررسی',cancelled:'لغوشده',refunded:'بازپرداخت‌شده',failed:'ناموفق'};
export default async function AccountPage({searchParams}) {
  const account = await customerAccount();
  const tab = (await searchParams).tab==='orders'?'orders':'overview';
  if(!account)return <AuthFrame><section className="auth-panel"><span className="eyebrow">حساب من</span><h1>به خانه‌چین خوش آمدید</h1><p>برای دیدن اطلاعات حساب و سفارش‌های خود وارد شوید.</p><div className="auth-actions"><StoreLink className="primary-action" href="/login">ورود به حساب</StoreLink><StoreLink href="/register">هنوز حساب ندارید؟ عضویت</StoreLink></div><p className="auth-foot">رمز را فراموش کرده‌اید؟ <StoreLink href="/forgot">بازیابی رمز</StoreLink></p></section></AuthFrame>;
  return <main className="shop-shell"><Breadcrumbs items={[{label:'حساب کاربری'}]}/><div className="account-layout"><aside className="account-sidebar"><Icon name="user"/><h2>{account.name}</h2><nav aria-label="بخش‌های حساب"><StoreLink href="/account" aria-current={tab==='overview'?'page':undefined}>پیشخوان حساب</StoreLink><StoreLink href="/account?tab=orders" aria-current={tab==='orders'?'page':undefined}>سفارش‌های من</StoreLink><StoreLink href="/favorites">علاقه‌مندی‌ها</StoreLink><StoreLink href="/forgot">تغییر رمز عبور</StoreLink><StoreLink href="/guide">راهنمای خرید</StoreLink></nav></aside><section className="account-home"><div className="account-top"><div><span className="eyebrow">حساب مشتری</span><h1>{tab==='orders'?'سفارش‌های من':'سلام، '+account.name}</h1><p dir="ltr">{account.email}</p></div><LogoutButton/></div>{tab==='overview'&&<><p>از اینجا سفارش‌های خود را پیگیری کنید و به انتخاب‌های ذخیره‌شده برگردید.</p><div className="account-stats"><StoreLink href="/account?tab=orders"><Icon name="order"/><b>{(account.orders?.length||0).toLocaleString('fa-IR')} سفارش</b></StoreLink><StoreLink href="/favorites"><Icon name="heart"/><b>علاقه‌مندی‌ها</b></StoreLink><StoreLink href="/shop"><Icon name="bag"/><b>ادامهٔ خرید</b></StoreLink></div><h2>آخرین سفارش‌ها</h2></>}{account.orders?.length?<div className="account-orders">{(tab==='orders'?account.orders:account.orders.slice(0,5)).map(order=><article key={order.id}><strong>سفارش #{Number(order.id).toLocaleString('fa-IR')}</strong><span>{statusLabels[order.status]||order.status}</span><span>{order.date}</span><b>{new Intl.NumberFormat('fa-IR').format(Number(order.total))} {order.currency==='IRR'?'ریال':['IRT','TOMAN'].includes(order.currency)?'تومان':order.currency}</b></article>)}</div>:<div className="empty-state"><div className="empty-symbol"><Icon name="bag"/></div><h2>هنوز سفارشی ندارید</h2><p>سفارش‌های متصل به این حساب پس از ثبت، اینجا نمایش داده می‌شوند.</p><StoreLink className="primary-action" href="/shop">دیدن محصولات</StoreLink></div>}</section></div></main>;
}
