export const orderStatuses={pending:'در انتظار پرداخت','on-hold':'در انتظار اقدام',processing:'در حال انجام',completed:'تکمیل‌شده',cancelled:'لغوشده',failed:'ناموفق',refunded:'بازپرداخت‌شده'};
export const addressKeys=['first_name','last_name','company','address_1','address_2','city','state','postcode','country'];
export const text=value=>String(value??'').replace(/<[^>]*>/g,'');
export function customerName(item){return [item.first_name||item.billing?.first_name,item.last_name||item.billing?.last_name].filter(Boolean).join(' ')||'مشتری بدون نام';}
export function customerDraft(item){return {first_name:item.first_name||'',last_name:item.last_name||'',...Object.fromEntries(['billing','shipping'].map(kind=>[kind,Object.fromEntries([...addressKeys,...(kind==='billing'?['email','phone']:[])].map(key=>[key,String(item[kind]?.[key]??'')]))]))};}
export function customerDiff(before,after){return Object.fromEntries(Object.entries(after).flatMap(([key,value])=>{if(key==='billing'||key==='shipping'){const changed=Object.fromEntries(Object.entries(value).filter(([field,v])=>v!==before[key]?.[field]));return Object.keys(changed).length?[[key,changed]]:[];}return value!==before[key]?[[key,value]]:[];}));}
export function orderStatusOptions(item){const current={[item.status]:orderStatuses[item.status]||item.status};if(['cancelled','failed','refunded'].includes(item.status))return current;return {...current,'on-hold':orderStatuses['on-hold'],...((item.date_paid||['processing','completed'].includes(item.status)||item.payment_method==='cod')?{processing:orderStatuses.processing,completed:orderStatuses.completed}:{}),cancelled:orderStatuses.cancelled};}
export function money(value,currency='IRT'){const n=Number(value);return `${Number.isFinite(n)?n.toLocaleString('fa-IR'):text(value)} ${({IRT:'تومان',IRR:'ریال',TOMAN:'تومان'})[currency]||currency}`;}
export function dateLabel(value){if(!value)return 'ثبت نشده';const d=new Date(/Z|[+-]\d\d:\d\d$/.test(value)?value:value+'Z');return Number.isNaN(d.getTime())?'ثبت نشده':d.toLocaleString('fa-IR',{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});}
