'use client';
import {useMemo,useState} from 'react';
import {catalogCategories,filterProducts} from '../../lib/catalog';
import {Breadcrumbs,EmptyState} from '../components/ui';
import ProductCard from '../components/product-card';
export default function CatalogView({products,error,category=null,initialQuery=''}) {
  const [query,setQuery]=useState(initialQuery),[stock,setStock]=useState(false),[min,setMin]=useState(''),[max,setMax]=useState(''),[sort,setSort]=useState('newest');
  const categories=catalogCategories(products);
  const visible=useMemo(()=>filterProducts(products,{query,category,stock,min,max,sort}),[products,query,category,stock,min,max,sort]);
  const title=category?.name||'همهٔ محصولات';
  return <main className="shop-shell"><Breadcrumbs items={[...(category?[{label:'دسته‌بندی‌ها',href:'/categories'}]:[]),{label:title}]}/><div className="catalog-layout"><details className="catalog-filter" open><summary>فیلتر محصولات</summary><div><label>جست‌وجو<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="نام محصول…" maxLength={100}/></label><label>دسته‌بندی<select value={category?.id||''} onChange={e=>window.location.assign(e.target.value?`/category/${e.target.value}`:'/shop')}><option value="">همهٔ دسته‌ها</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name} ({c.count.toLocaleString('fa-IR')})</option>)}</select></label><label><input type="checkbox" checked={stock} onChange={e=>setStock(e.target.checked)}/>فقط کالاهای موجود</label><label>حداقل قیمت ({products[0]?.unit||'تومان'})<input type="number" min="0" value={min} onChange={e=>setMin(e.target.value)} inputMode="numeric"/></label><label>حداکثر قیمت ({products[0]?.unit||'تومان'})<input type="number" min="0" value={max} onChange={e=>setMax(e.target.value)} inputMode="numeric"/></label><button onClick={()=>{setQuery('');setStock(false);setMin('');setMax('');setSort('newest');}}>پاک‌کردن فیلترها</button></div></details><section><div className="catalog-toolbar"><div><h1>{title}</h1><p role="status">{visible.length.toLocaleString('fa-IR')} محصول</p></div><select aria-label="مرتب‌سازی محصولات" value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">جدیدترین‌ها</option><option value="cheap">ارزان‌ترین</option><option value="expensive">گران‌ترین</option></select></div>{query&&<p className="catalog-active">نتایج جست‌وجوی «{query}»</p>}{error?<div className="form-error" role="alert">{error} <a href="/shop">تلاش دوباره</a></div>:visible.length?<div className="craft-products">{visible.map(p=><ProductCard key={p.id} product={p}/>)}</div>:<EmptyState icon="search" title="محصولی پیدا نشد" href="/shop" action="نمایش همهٔ محصولات">عبارت جست‌وجو یا محدودهٔ قیمت را تغییر دهید. می‌توانید فیلتر موجودی را هم بردارید.</EmptyState>}</section></div></main>;
}
